version: "3.9"

services:
  alice-gpt:
    build: .
    container_name: alice-gpt
    restart: unless-stopped

    ports:
      - "127.0.0.1:3002:8080"

    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
      OPENROUTER_GPT_NAME: "${OPENROUTER_GPT_NAME}"

    logging:
      options:
        max-size: "10m"
        max-file: "3"
